### ISSUE TITLE
Confusing Alphanumeric Characters to Avoid in IDs?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/cid#2]
Most computer scientists or "_developers_" consider the "happy path" when building software
and don't get to see the "other side" ... I have seen _all_ aspects of the "stack" from having worked in "***customer service***" (_call centres_) and had to field calls from **_angry_/_frustrated_ people**.
Putting in a little bit more effort up-front to create human-friendly IDs pays later.
I feel that the _default_ needs to be _usability_ and _accessibility_; that's why this issue exists.

# Todo 

+ [ ] _Auto-generated_ IDs should exclude certain "confusing" characters 
to avoid confusing people who are _reading_ or _typing_ them. 
> For example: **0** (zero) looks like **O** (Capital o) and **I** (capital i) looks like **l** (lower-case L).
  + [ ] Collate full list of "confusing characters"
  + [ ] Calculate probability of collision when using reduced character set

# Recommended Reading

+ [ ] https://ux.stackexchange.com/questions/53341/are-there-any-letters-numbers-that-should-be-avoided-in-an-id
+ [ ] https://ux.stackexchange.com/questions/21076/are-there-numbers-and-letters-to-avoid-for-activation-codes-via-sms
+ [ ] https://typography.guru/journal/letters-symbols-misrecognition/
+ [ ] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3541865/
+ [ ] https://stackoverflow.com/questions/11919708/set-of-unambiguous-looking-letters-numbers-for-user-input

**Comment by nelsonic** [comment]
GOTO: https://en.wikipedia.org/wiki/Base58

**Comment by nelsonic** [comment]
Basically,  what I'm describing is **`Base56`**
I _love_ it when the thing I'm thinking about _already_ has a name and "_validation_"!
The _worst_ thing is being "original" (_i.e. "crazy"_) and having to "convince" people of an idea!
This is _soooooo_ much more time-effective. 
Just go read this wikipedia article that someone **`else`** wrote! 🎉
